# Generated by Django 3.1.1 on 2020-09-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='postImage',
        ),
    ]
