# Generated by Django 3.1.1 on 2020-09-28 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0004_post_post_audience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='Post',
            new_name='postid',
        ),
        migrations.AddField(
            model_name='postimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
