# Generated by Django 3.1.1 on 2020-09-28 13:01

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20200928_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_audience',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Profile.models.upload_path),
        ),
    ]
