# Generated by Django 3.1.1 on 2020-10-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20201010_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_date',
        ),
    ]
