# Generated by Django 3.1.1 on 2020-10-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
    ]
