# Generated by Django 3.1.1 on 2020-10-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_remove_comments_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
