# Generated by Django 3.1.1 on 2020-09-11 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+')], max_length=20)),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=20)),
                ('contact_audience', models.CharField(max_length=20)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.ImageField(default='defaultProfilePic.png', upload_to='')),
                ('permCountry', models.CharField(max_length=30)),
                ('permState', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=30)),
                ('permDistrict', models.CharField(max_length=30)),
                ('permCity', models.CharField(max_length=30)),
                ('tempCountry', models.CharField(max_length=30)),
                ('tempState', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=30)),
                ('tempDistrict', models.CharField(max_length=30)),
                ('tempCity', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profielDetails',
            },
        ),
    ]
