# Generated by Django 3.1.1 on 2020-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
