# Generated by Django 3.1.1 on 2020-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_auto_20200912_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(default='images/defaultProfilePic.png', upload_to=''),
        ),
    ]
