# Generated by Django 3.1.1 on 2020-09-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0003_auto_20200927_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(default='/images/defaultProfilePic.png', upload_to=''),
        ),
    ]
