# Generated by Django 3.1.1 on 2020-10-10 17:20

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAuthentication', '0004_auto_20200928_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiledetails',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='last_donated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
